apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  # - host: edu.whitestack.com
  - host: edu.minikube.com
    http:
      paths:
      - path: /heavywork
        pathType: Prefix
        backend:
          service:
            name: web-app-svc
            port:
              number: 8080