apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sc-{{ .Release.Name }}  # Nombre del Deployment con el sufijo del release
  labels:
    app: app-sc  # Etiqueta est치tica para la aplicaci칩n
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-sc  # Etiqueta est치tica para el selector
  template:
    metadata:
      labels:
        app: app-sc  # Etiqueta est치tica para los pods
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
