{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-sc-{{ .Release.Name }}  # Nombre del Ingress con el sufijo del release
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /heavywork
            pathType: Prefix
            backend:
              service:
                name: app-sc-{{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
          - path: /lightwork
            pathType: Prefix
            backend:
              service:
                name: app-sc-{{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: app-sc-{{ .Release.Name }}
                port:
                  number: {{ .Values.service.metricsPort }}
{{- end }}
