apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sc-apps-hpa
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-sc-sc-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metric:
        name: heavywork_requests_total
      describedObject:
        apiVersion: v1
        kind: Service
        name: app-sc-sc-app
      target:
        type: Value
        value: "10" # Umbral de 10 peticiones por segundo
