apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sc-app-srv-mon
  namespace: apps
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /metrics  
  selector:
    matchLabels:
      app: app-sc
